# These are supported funding model platforms

github: [vanosoft]
patreon: https://www.patreon.com/talismanchet
open_collective: https://opencollective.com/talismans-collective
ko_fi: https://ko-fi.com/talismanchet
